### ISSUE TITLE
[Bug]: Login Timeout does not increase on 1.21.1

### ISSUE THREAD

**Issue by suerion** [someaddons/connectivity#100]
### Describe the bug you're experiencing

Hey, i had a big modpack, with 280 Mods (ingame loaded 506) on login i would custom payloads work on my modpack.

But i had to disable Polymer Mods, to load the server faster. Polymer load something above the custom payloader, but it is not fast enough.

I had tried to increase the timeout login time, but it does not increase it. i Had tried 300+ seconds, but it does not take the time i had added in the settings.

This issue, the Login need longer as default Minecraft time is only with polymer mods. after disabling, it load faster, but your Timeout timer does not increase.

### Reproducability

Start Server with mod and Custom Payloader like Polymer Mods, it does allways disconnect me with Timeout,

Polymer Mods need more time to load, i had tried to increase the time, but Login allways timeouted with default Minecraft time

Without Polymer Mods, i had no issue, but i don't need more time with polymer

[disconnect-2024-09-14_16.23.33-client.txt](https://github.com/user-attachments/files/17007045/disconnect-2024-09-14_16.23.33-client.txt)
[client - latest.log](https://github.com/user-attachments/files/17007046/client.-.latest.log)
[latest.log](https://github.com/user-attachments/files/17007048/latest.log)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Fabric

### Logs

Logs are above

**Comment by someaddons** [comment]
should be fixed in the newest(5.8) if not please open a new report :)
