### ISSUE TITLE
[Bug]:  incompatibility with theurgy

### ISSUE THREAD

**Issue by schindlershadow** [someaddons/connectivity#103]
### Describe the bug you're experiencing

 Getting disconnected randomly from theurgy caloric_flux_emitter follow_projectile
 ```
Description: Packet handling error

java.lang.IllegalStateException: Invalid entity data item type for field 10 on entity FollowProjectile['entity.theurgy.follow_projectile'/5205, l='ClientLevel', x=-18420.57, y=35.00, z=-8028.71]: old=(-18440.5, 65.5, -8050.5)(class net.minecraft.world.phys.Vec3), new=[net.minecraft.core.particles.ColorParticleOption@5bd3a823](class java.util.ArrayList)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.syncher.SynchedEntityData.assignValue(SynchedEntityData.java:125) ~[client-1.21.1-20240808.144430-srg.jar%23431!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.syncher.SynchedEntityData.assignValues(SynchedEntityData.java:115) ~[client-1.21.1-20240808.144430-srg.jar%23431!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
```

**Screenshots**
![image](https://github.com/user-attachments/assets/c8678b1b-e42f-497f-b93d-d662dded166e)

- Theurgy Version: theurgy-1.21.1-neoforge-1.56.0
- OS: windows 10
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/infinix-test

bug report with theurgy:
https://github.com/klikli-dev/theurgy/issues/223

### Reproducability

    Place caloric_flux_emitter connected to some block
    wait for DC

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Forge

### Logs

https://pastebin.com/raw/htLrL7Qj

**Comment by someaddons** [comment]
ye that is unrelated to connectivity, synchedentitdata issues are always caused by mod compat problems where mods are mixin additional synchedentitydata in. Connectivity itself does not touch synchedentitydata
