### ISSUE TITLE
[Bug]: payload still too large

### ISSUE THREAD

**Issue by awsumMoth** [someaddons/connectivity#105]
### Describe the bug you're experiencing

i installed the mod on my server and on the client and it still says "Payload may not be larger than 104857 bytes". 
[debug.log](https://github.com/user-attachments/files/17526746/debug.log)

### Reproducability

be on a server with a payload larger than 104857 bytes.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

[latest.log](https://github.com/user-attachments/files/17526747/latest.log)

**Comment by someaddons** [comment]
@awsumMoth 
could you reproduce the error with the "debugPrintMessages" config option enabled? Then it'll actually print some sources to the log that indicate the problem

**Comment by someaddons** [comment]
try 6.0, and if its still an issue please open a new report
