### ISSUE TITLE
[Feature Request]: Command - Print qualified class names for packets in summary

### ISSUE THREAD

**Issue by ByThePowerOfScience** [someaddons/connectivity#106]
## Reason

It's MCreator, it's always MCreator.

Basically, every MCreator mod's packet has the exact same class name: `SavedDataSyncMessage`.  The only difference is the package and enclosing class.

The problem is, Connectivity's commands only show the simple class name ("SavedDataSyncMessage"), so there's no way to know which one specifically is being oversent besides going through with a packet sniffer and cross-referencing the payloads.  And when every other mod nowadays is secretly an MCreator mod, all of them potentially DDOSing the client, it's a _lot_ of work to go through.

## Suggested Solution

Use the fully-qualified class name of the packets (i.e. `net.mcreator.ddos.Networking.SavedDataSyncMessage`) in the map instead of just the simple name, then allow people to view the full name with an added argument like `connectivity packetSummary (minutes) (--full-name)`.

### Minecraft version

1.20.1

### Modloader version

Forge

**Comment by someaddons** [comment]
since 1.21 does switch to actual ID's I dont think its worth the effort to add this soley for 1.20.1 and mostly mccreator. I'd recommend to not use mccreator mods anyways
