### ISSUE TITLE
[Bug]: Player already online!

### ISSUE THREAD

**Issue by VitasLoWang** [someaddons/connectivity#107]
### Describe the bug you're experiencing

So there is one player who has not fast enough connection and he regularly does not get the world loaded before this default silly one minute timeout hits. So that was the reason I installed this mod hoping it will mitigate the issue, but there is another problem!
He could connect but after around half an hour of play I see he got disconnected and there is this in the console

[18:57:12] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@24c4fb81[id=547474f3-532f-3048-bf7d-0d284aed59f4,name=penguincz98,properties={},legacy=false] (/77.48.177.140:54891): §cPlayer literal{penguincz98} is already online!
[18:57:12] [Server thread/INFO]: com.mojang.authlib.GameProfile@24c4fb81[id=547474f3-532f-3048-bf7d-0d284aed59f4,name=penguincz98,properties={},legacy=false] (/77.48.177.140:54891) lost connection: §cPlayer literal{penguincz98} is already online!
[18:57:13] [Server thread/WARN]: handleDisconnection() called twice
[18:57:18] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@2e63827a[id=547474f3-532f-3048-bf7d-0d284aed59f4,name=penguincz98,properties={},legacy=false] (/77.48.177.140:54895): §cPlayer literal{penguincz98} is already online!

whenever he tried to login he gets this message about being already online, but he is not from his point of view!
I have removed the mod, but then he could not login anyway because of the timeout

### Reproducability

this one player tries to connect when the mod is active. Other players connect just fine.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/VitasLoWang/5ac2afc25e9675456327ceb04abdc51f

**Comment by VitasLoWang** [comment]
it is possible that was only one time. Today that player connects without such problem...

**Comment by someaddons** [comment]
Could you send me your connectivity.json config file?

**Comment by VitasLoWang** [comment]
```
{
  "disableLoginLimits": {
    "desc:": "Should login packet size limits be disabled? Error:(IOException(\"Payload may not be larger than 1048576 bytes\")) default:true",
    "disableLoginLimits": true
  },
  "disablePacketLimits": {
    "desc:": "Should play packet size limits be disabled? Error:(Badly compressed packet) default:true",
    "disablePacketLimits": true
  },
  "disableChatVerificationDisconnect": {
    "desc:": "(Clientside) Disables players disconnecting on chat message verification problems,(enable debugPrintMessages to see the message causing issues). default:true",
    "disableChatVerificationDisconnect": true
  },
  "debugPrintMessages": {
    "desc:": "Enable addition debug logging for networking errors. default:false",
    "debugPrintMessages": false
  },
  "logintimeout": {
    "desc:": "Set the max login timeout in seconds. default = 120",
    "logintimeout": 180
  },
  "disconnectTimeout": {
    "desc:": "Set the ingame disconnect timeout for disconnecting players. Default = 60sec",
    "disconnectTimeout": 60
  },
  "packetHistoryMinutes": {
    "desc:": "Set the amount of minutes for which network packet history data is saved. Default = 5 minutes",
    "packetHistoryMinutes": 5
  },
  "showFullResourceLocationException": {
    "desc:": "Enable to see the full log output for all resource location exceptions. Default = false",
    "showFullResourceLocationException": false
  }
}
```

after that I changed this back to default
"logintimeout": 120
but not sure this could be related

**Comment by VitasLoWang** [comment]
happened today again to another player which usually has bad ping and lags. I kicked him via console and then he could connect

**Comment by VitasLoWang** [comment]
it has become unusable. Today another two players which never had problem with ping have this error and can't join

**Comment by VitasLoWang** [comment]
https://gist.github.com/VitasLoWang/41d52c67113fbfbc15bac3743206dbc8

**Comment by VitasLoWang** [comment]
is this mod only server side or to players need it installed? Does it make a difference? Now I had it only on server

**Comment by someaddons** [comment]
serverside only is fine, but you probably also should try updating xD

**Comment by VitasLoWang** [comment]
the new version 6.0 does not change anything. It still does say "player is already online" for several different players when they get disconnected by lag or they disconnect manually and then try to connect back

**Comment by someaddons** [comment]
should be fixed in 6.1

**Comment by BelgianDev** [comment]
Hey there is a similar issue on forge 1.20.1-6.1, when the player times-out the server still thinks that the player is online, they disconnect when forcefully kicked or server is stopping, only then the server updates that the player actually got disconnected.

Should I create a new issue for this ?

**Comment by Iker21dev** [comment]
oh god, I had this problem and I never knew how to detect what caused it, we are 16 players and approximately half of them had this problem.

**Comment by Iker21dev** [comment]
oh god, I had this problem and I never knew how to detect what caused it, we are 16 players and approximately half of them had this problem.

**Comment by someaddons** [comment]
> Hey there is a similar issue on forge 1.20.1-6.1, when the player times-out the server still thinks that the player is online, they disconnect when forcefully kicked or server is stopping, only then the server updates that the player actually got disconnected.
> 
> Should I create a new issue for this ?

ye if it still appears in 6.1
