### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Xadev3497** [someaddons/connectivity#108]
Hi, i don't know if this is the right place to post this, but since **_Connectivity mod threw some warnings_** i thought people from here can help me the most as the know why it sent those warnings/errors and what it is related to.
So.. i'm hosting modded minecraft server (on my PC), and i started it that day at 18:55:22, after last player disconnected at 20:26:28 server was running for nearly 40 minutes then as seen in below attached debug.log **_at line 13491_** (i think) connectivity sent some warnings, which at my first glance wasn't anything worrying, but (after seeing it at 00:39) i tried to join "still running" server it crashed due to being overloaded (3131 ticks behind) which isn't a problem on a daily basis as i got only 50ticks behind AT MAX 
[debug.log](https://github.com/user-attachments/files/17807595/debug.log)

Also my modpack on which it crashed is public so here is a [link to it](https://www.curseforge.com/minecraft/modpacks/build-n-explore-adventure) running on latest version of it (V1.4.4)
2-nd Also (xD) i should mention that on modpack version V1.3 everything was fine.. It was the changes made in 1.4 from when it caused errors
And now (02:02) i can't join my server as my "joining" screen stop at "Connecting server" and then timed out
sorry that i seek help here as i don't know where else. if you want to suggest where i should go with it, please tell me

**Comment by someaddons** [comment]
[19lis2024 00:39:43.402] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 156578ms or 3131 ticks behind

Your server just timed out due to lag, nothing to do with those network errors, check the crash report it generated
