### ISSUE TITLE
[BUG] Potential Incompatibility - Timeout when joining a second time

### ISSUE THREAD

**Issue by SirOMGitsYOU** [someaddons/connectivity#11]
**Mod file version**
connectivity-2.4-1.16.5

**Describe the bug**
A clear and concise description of what When using a large modpack with connectivity in it if you were to try host a forgebukkit/spigot server using one of the various options out there

(Magma, Mohist, Loliserver, Arclight)

**To Reproduce**
1. Use a large modpack (in my test i used https://www.curseforge.com/minecraft/modpacks/a-bit-of-everything-official/files/3574154)
2. Use LoliServer (https://github.com/Loli-Server/LoliServer1.16 - currently only stable one for 1.16) 
3. boot up the server (remove any clientside mods)
4. join server, you will successfully join the first time,
5. disconnect
6. re-join the server and you will infinitely timeout from here on out.

**Expected behavior**
Not to timeout and the connection timeout to increase
(have also increased the timeout to match in all configs relating to the timeout including disabling other mods that change the time out such as randompatches and performant with still replicating issue, only occurs on forgebukkit servers as on normal forge no issues at all)

**Comment by someaddons** [comment]
I'm making my mods for forge, so only supporting forge not other forge forks with who knows what changes to the base game.

**Comment by ckhawks** [comment]
I'm having this same problem with a large modpack on Forge 36.2.26. It doesn't seem like it's necessarily linked to joining the server for the second time, as I'm having the same issue trying to connect to the server for the first time since opening the client.

[latest.log](https://github.com/someaddons/connectivity/files/8028489/latest.log)

**Comment by ckhawks** [comment]
Unfortunately I don't :( I'm sure I have a similar issue with one mod
somewhere causing the problem, but I am stuck on how to diagnose it
