### ISSUE TITLE
[Bug]: Neo 1.21.1 Client Crash at Startup - 6.1

### ISSUE THREAD

**Issue by Soforak** [someaddons/connectivity#113]
### Describe the bug you're experiencing

I'm on Neoforge 21.1.89 and same bug was on previous versions, the game works fine with connectivity 6.0 and crash with version 6.1

### Reproducability

Update Connectivity from 6.0 to 6.1
Launch the game
The game crash

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Forge

### Logs

https://gist.github.com/Soforak/47aaf899d84fd07ea8cea25d2fae103e

**Comment by someaddons** [comment]
bettermodsbutton is crashing due to some problem with its config file, dont think this has anything to do with connectivity. Probably just need to reset that faulty config file

**Comment by someaddons** [comment]
There is btw a compat issue with vmp, the fabric version of the mod got a fix for it, I wouldnt recommend using syntra connector.

**Comment by Soforak** [comment]
Deleting VMP solved the issue, I don't have many players on the server as it was only working on client side, so it's not a big lose anyways, Thanks!
I didn't try to use the fabric version tho
