### ISSUE TITLE
Payload to big

### ISSUE THREAD

**Issue by Waurick** [someaddons/connectivity#12]
**Mod file version**
connectivity-2.4-1.16.5

**Describe the bug**
kicked from the server with this error Message
![unknown](https://user-images.githubusercontent.com/71395103/147856453-cba0d2a1-50a3-494f-bf43-c99dd90b7939.png)

**To Reproduce**
It is not that easy. You have to use a storage mod like refined storage. I used Occultism. Put in an Item with big NBT Data. In my Case, a Minecart Contraption full of Items from the Mod Create.

**Expected behavior**
taking it out.

**Workaround**
I have to get it out using a Hopper.

**Comment by someaddons** [comment]
do you have connectivity on both sides? I'll need logs of both server and client from the time the error happens, preferably with the debug config option set to true: `debugPrintMessages = true`

**Comment by Waurick** [comment]
It is installed on both sides. No debug messages(I didn't include them with intention. I read through them, there was nothing). The Error is Server side. Can you increase the max Payload?

**Comment by someaddons** [comment]
connectivity makes the size not limited, but isntead logs warnings. Without the logs during the time of the issues I won't be able to help
