### ISSUE TITLE
Support: Overlap with AntiGhost?

### ISSUE THREAD

**Issue by Boobies** [someaddons/connectivity#14]
I'm sorry that this is a support question rather than a bug support but the comment section on the CurseForge paged is closed. This mod advertises to help with ghost block. Is there an overlap with the mod AntiGhost? Does it help to use both?

**Comment by Boobies** [comment]
For the record, that mod offers a `/ghost` command to ask the server to resend the blocks around the player. What precisely does this mod do regarding ghosting?

**Comment by someaddons** [comment]
it simply fixes the reason for ghost blocks appearing
