### ISSUE TITLE
Crash server side with create

### ISSUE THREAD

**Issue by lebanni** [someaddons/connectivity#2]
**Mod file version**
The exact name of the mod file version.
connectivity-1.6-1.16.5.jar
create-mc1.16.5_v0.3.1c.jar

**Describe the bug**
Crash starting the server involving create.

Crashlog :
https://pastebin.com/7CvctKQF

**Comment by someaddons** [comment]
crash with randompatches, not create

**Comment by sirben99** [comment]
Can confirm that when RandomPatches, Connectivity and Create are put together, Create doesent load. Removing any one of them works, meaning they work indivicually, but not together.

Forge: 36.1.24
Minecraft: 1.16.5
Connectivity: 1.6-1.16.5
Create: 1.16.4+ v0.3.1c
RandomPatches: 2.4.4-forge

Crash.txt;
[crash-2021-06-03_19.28.15-fml.txt](https://github.com/someaddons/connectivity/files/6593085/crash-2021-06-03_19.28.15-fml.txt)

Latest.log:
[latest.log](https://github.com/someaddons/connectivity/files/6593086/latest.log)

**Comment by someaddons** [comment]
its randompatches thats crashing though, its on them to solve. Connectivity doesnt cause any crashes when it cannot apply some modifications

**Comment by someaddons** [comment]
Added a description for config settings to avoid the crash to the mod page
