### ISSUE TITLE
[Compatibility Issue]: Crash on startup with ?

### ISSUE THREAD

**Issue by HacoKavanah** [someaddons/connectivity#20]
### Describe the bug you're experiencing

I downloaded this mod to my modpack and it crashed! Turning the mod off allowed the game to launch.

### Reproducability

I assume it is a compatibility issue with some mod.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

https://gist.github.com/HacoKavanah/d0a5e13ce9661adf97ad0b05e6c5bc19

**Comment by someaddons** [comment]
its not compatible with the timeoutout mod, as that one has the same login timeout modifications
