### ISSUE TITLE
[Bug]: Can not connect to servers with this mod enabled

### ISSUE THREAD

**Issue by keatit71** [someaddons/connectivity#21]
### Describe the bug you're experiencing

The servers just say they are not online, I expected them to be online.

### Reproducability

Install this mod on 1.18.2 and try to connect to a server

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

https://gist.github.com/keatit71/4b20eacfa73445c07de262b47baf286b

**Comment by keatit71** [comment]
Minecraft version 1.18.2 not 1.18.1 since there is no option for it.

**Comment by someaddons** [comment]
check if version 2.9 fixes it for you please

**Comment by someaddons** [comment]
nice, ye gonna include that in the next version
