### ISSUE TITLE
[Bug]: Incompatible with Universal Graves/Polymer

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [someaddons/connectivity#22]
### Describe the bug you're experiencing

**MC** 1.18.2, there's no option to select it in the drop-down menu

When [Universal Graves](https://www.curseforge.com/minecraft/mc-mods/universal-graves) and Connectivity are installed together, the game will crash upon generating world. Affects both clients and servers. The crash log references Polymer, which is a library Universal Graves uses: https://www.curseforge.com/minecraft/mc-mods/polymer.

### Reproducability

1. Install both [Universal Graves](https://www.curseforge.com/minecraft/mc-mods/universal-graves) and Connectivity
2. If you are testing the client, you need to launch the game and create/join a single-player world
    If you are testing the server, just start the server
3. Both crash when loading the world

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

https://gist.github.com/Footage2-Amply-Pounce/4139c413af766fa12464408bff29d568

**Comment by Sunconure11** [comment]
@someaddons 

Might want to take a look at this.

**Comment by someaddons** [comment]
fixed in 3.3
