### ISSUE TITLE
Removed timeoutout, still crashes the game!

### ISSUE THREAD

**Issue by HacoKavanah** [someaddons/connectivity#23]
[crash-2022-05-02_00.52.35-server.txt](https://github.com/someaddons/connectivity/files/8599840/crash-2022-05-02_00.52.35-server.txt)
[crash-2022-05-02_00.52.49-client.txt](https://github.com/someaddons/connectivity/files/8599841/crash-2022-05-02_00.52.49-client.txt)

**Comment by someaddons** [comment]
```	Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getKeepAlivePacketInterval(J)J in timeoutout.mixins.json:ServerPlayNetworkHandlerKeepAliveMixin from mod timeoutout failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap timeoutout-refmap.json```

You still got the timeoutout mod :D

**Comment by HacoKavanah** [comment]
Yea lol, it was midnight so I think I accidentally removed a different one lol. Thanks for the help!
