### ISSUE TITLE
[Bug 1.18.2]: World Generation Issues

### ISSUE THREAD

**Issue by Reshy** [someaddons/connectivity#24]
### Describe the bug you're experiencing

Having issues with the world failing to generate past the initial spawn zone with this mod enabled.  Might be a conflict with another mod but I'm unsure.  

### Reproducability

Loading into a world and then moving around causes the world to stop generating and be unable to save and exit.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

Doesn't show in the log.

**Comment by someaddons** [comment]
this mod has zero effect on worldgen though, what makes you think it is related?

**Comment by Reshy** [comment]
Only happened after it was updated, though I'm trying to figure out if it was an issue that happened before I updated it and I didn't notice it before.
