### ISSUE TITLE
[Bug]: Connectivity Fabric-1.18.2-2.8 prevents the server from registering as online

### ISSUE THREAD

**Issue by RoseTheFoxGit** [someaddons/connectivity#25]
### Describe the bug you're experiencing

I have installed the latest version of Connectivity for Fabric 1.18.2 along side my other mods in my mod-pack and I started up the server, and I am unable to connect to the server, as the server is online locally but will not register online elsewhere. No one else, including me are able to connect or see the server online.

Mods List: [https://pastebin.com/HGeBSFg5](url)
Video showing off the issue: [https://www.youtube.com/watch?v=BAtlyC4SZDE](url)

### Reproducability

Download and Install the latest version of Connectivity for Fabric into a modded dedicated server.
Start up the dedicated server, and try to connect to it.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

There are no found logs or crash reports.

**Comment by someaddons** [comment]
interesting, now its failing for me aswell on a 1.18.1 server, tried with 1.18.2 earlier

**Comment by someaddons** [comment]
try version 2.9 once its approved, I think that should fix it(did for me at least)

**Comment by RoseTheFoxGit** [comment]
After applying the patch, the server now appears online but once you attempt to connect to it, you are met with a blank disconnect error, with the console showing "handleDisconnection() called twice"

Image1: [https://i.imgur.com/4YY6TDi.png](url)
Image 2: [https://i.imgur.com/BYRl3Jw.png](url)
Image 3 (Showing the server online): [https://i.imgur.com/z2yKPB9.png](url)

**Comment by someaddons** [comment]
now that is probably to do with another mod xD, turn on debugPrintMessages to true in the config (needs a restart) to see the actual error in the log

**Comment by RoseTheFoxGit** [comment]
This is still the only error that shows up: [https://i.imgur.com/LUaJiLS.png](url)

There is nothing else going on in the console/logs, and no crash reports; I have no other mods that mess with the networking stack other than Krypton and Krypton doesn't affect Connectivity

**Comment by someaddons** [comment]
it works with Krypton ye, though you never know really which other mods may do stuff aswell

**Comment by RoseTheFoxGit** [comment]
I haven't seemed to find any logs, or anything else that messes with networking that is causing this issue; I don't know what else to try out.

**Comment by RoseTheFoxGit** [comment]
> I haven't seemed to find any logs, or anything else that messes with networking that is causing this issue; I don't know what else to try out.

Update: After doing lots of testing going through each and every individual mod in my pack, it seems like Debugify causes network conflict for whatever reason with Connectivity, preventing users from joining the server. If you know what's up with that, please explain it to me because I am in an entire world of confusion.

Debugify: [https://www.curseforge.com/minecraft/mc-mods/debugify](url)

**Comment by someaddons** [comment]
stuff gets very weird when networkstuff is messed up xD if its debugify conflicting that gonna help a lot finding it

**Comment by RoseTheFoxGit** [comment]
Are you able to explain the other things? I don't have debugify on the server and those other issues I have below the debugify curseforgelink are happening every once in a while.

**Comment by someaddons** [comment]
its just the normal message of a client disconnecting, you just see it due to debug  config log ouput

**Comment by RoseTheFoxGit** [comment]
Well, if you install debugify along with the fabric-api, it seems to give errors with connectivity. I have removed debugify from my server for now as it was causing other issues too it seems. Everything else with connectivity is working A-Okay, and with your mod; one of my friends who has less than 3MB Down/Up is now able to play on my server. Cheers! (If there's nothing else you want to know, feel free to close this issue report, thank you so much for creating this wonderful mod!)

**Comment by someaddons** [comment]
glad its working now :D, also thanks for the reports always helps narrowing down issues
