### ISSUE TITLE
[Bug]: i can't join a server because of packet size problem even with mod installed.

### ISSUE THREAD

**Issue by netcore10** [someaddons/connectivity#27]
### Describe the bug you're experiencing

Saw the error, installed the mod, it didn't really help? Am i roadblocked.

### Reproducability

I don't really know. You can try my modpack at 
https://www.curseforge.com/minecraft/modpacks/haywen-unity-fe
with connectivity and see if you can join a server.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

https://gist.github.com/netcore10/fb66d1e2007b543f6f2d91c16da989fc

**Comment by someaddons** [comment]
I need the full log of both sides to help further

**Comment by netcore10** [comment]
Sure! 

Client
[latest_client.log](https://github.com/someaddons/connectivity/files/8691556/latest_client.log)
Server
[logs_latest_server.log](https://github.com/someaddons/connectivity/files/8691557/logs_latest_server.log)

**Comment by netcore10** [comment]
it didn't catch the end of the log, there's a lot of repeated 

[17:02:07] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[17:02:07] [Netty Epoll Server IO #3/WARN]: Network error for:packet_handler
io.netty.channel.StacklessClosedChannelException: null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source) ~[netty-all-4.1.68.Final.jar:?]
when connectivity advanced logging enabled.

**Comment by someaddons** [comment]
seems like REI is sending too much data

**Comment by netcore10** [comment]
But shouldn't the packet size be overwritten?

**Comment by netcore10** [comment]
is this a me problem, or is it a mod problem? I've kinda been roadblocked. XL packets sends me to this mod, but this mod doesn't seem to be the fix i need, even xl packets doesn't fix the packet issue. I'm a bit out of options, and a little desperate, do you know of any solution?

**Comment by someaddons** [comment]
both XL packets and connectivity size limits are just masking the problem, the problem is that one mod is doing sth bad. Ideally you find which mod is causing it and get that mod to fix it

**Comment by netcore10** [comment]
Dang, that might be hard considering each mod you remove can lower the packet size xD

**Comment by aking4125** [comment]
Try disabling [Forgero](https://www.curseforge.com/minecraft/mc-mods/forgero)

I have a similar issue as reported [here](https://www.reddit.com/r/fabricmc/comments/ut6uo4/1182_client_refuses_to_connect_to_server_just_dcs/) but for me it's [Jello](https://www.curseforge.com/minecraft/mc-mods/jello) (Which requires [oωo (owo-lib)](https://www.curseforge.com/minecraft/mc-mods/owo-lib) Which we both have installed 0.7.2). 

However Jello 3.2.5 without Forgero causes the same issue. So there's an odd conflict somewhere. I haven't tested Forgero with oωo (owo-lib) but I'm still looking into it.

**Comment by netcore10** [comment]
> Try disabling [Forgero](https://www.curseforge.com/minecraft/mc-mods/forgero)
> 
> I have a similar issue as reported [here](https://www.reddit.com/r/fabricmc/comments/ut6uo4/1182_client_refuses_to_connect_to_server_just_dcs/) but for me it's [Jello](https://www.curseforge.com/minecraft/mc-mods/jello) (Which requires [oωo (owo-lib)](https://www.curseforge.com/minecraft/mc-mods/owo-lib) Which we both have installed 0.7.2).
> 
> However Jello 3.2.5 without Forgero causes the same issue. So there's an odd conflict somewhere. I haven't tested Forgero with oωo (owo-lib) but I'm still looking into it.

I'll give it a shot.

**Comment by netcore10** [comment]
> > Try disabling [Forgero](https://www.curseforge.com/minecraft/mc-mods/forgero)
> > I have a similar issue as reported [here](https://www.reddit.com/r/fabricmc/comments/ut6uo4/1182_client_refuses_to_connect_to_server_just_dcs/) but for me it's [Jello](https://www.curseforge.com/minecraft/mc-mods/jello) (Which requires [oωo (owo-lib)](https://www.curseforge.com/minecraft/mc-mods/owo-lib) Which we both have installed 0.7.2).
> > However Jello 3.2.5 without Forgero causes the same issue. So there's an odd conflict somewhere. I haven't tested Forgero with oωo (owo-lib) but I'm still looking into it.
> 
> I'll give it a shot.

You just saved my life.

**Comment by aking4125** [comment]
@netcore10 No worries. But I wanted to know why first. It just doesn't make sense. Also Jello 3.2.5 does the same thing so there must be something else.

@someaddons Would something like this be patched into Connectivity somehow? Probably?

**Comment by netcore10** [comment]
> @netcore10 No worries. But I wanted to know why first. It just doesn't make sense. Also Jello 3.2.5 does the same thing so there must be something else.
> 
> @someaddons Would something like this be patched into Connectivity somehow? Probably?

might wanna add an issue to jello, i've contacted forgeo
