### ISSUE TITLE
[Bug]: causing server to crash

### ISSUE THREAD

**Issue by littlepianist** [someaddons/connectivity#30]
### Describe the bug you're experiencing

when the ceaseless impetus from malum mod activates the server will crash but it is caused by connectivity

### Reproducability

hold and ceaseless imetus on the left hand and try to die
server died instead

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/littlepianist/5cecd5fa27e64a40c1bcf22776f40dfe

**Comment by littlepianist** [comment]
after discussion with the owners of ItShallNotTick and Malum, I think the cause of the crash should be Connectivity

**Comment by someaddons** [comment]
I can reproduce the crash 100% with only forge+ malum, sooo yea not a connectivity issue.
ceaseless imetus into offhand, and die to mob damage -> crash
