### ISSUE TITLE
[Need Help]: 1.18.2 Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null

### ISSUE THREAD

**Issue by aking4125** [someaddons/connectivity#31]
### Describe the bug you're experiencing

Hello,

Upon attempting to join the server. The client disconnects with the following message:
![image](https://user-images.githubusercontent.com/11141831/171694174-264e637e-dabf-4f1e-adc5-aa276857893b.png)

Below is the server debug.log file (Compressed into .zip cause Github has a 25MB Limit. (Also uploaded as a Gist)
[serverdebug.zip](https://github.com/someaddons/connectivity/files/8826405/serverdebug.zip)

And here is the client debug.log file. There seems to be some useful information but for some reason parts of the file got messed up each time.
[debug.log](https://github.com/someaddons/connectivity/files/8826408/debug.log)

I understand this isn't directly related to Connectivity but I do need some help identifying the issue if possible

### Reproducability

1. Join server (Either dedicated or LAN)
2. Get kicked

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/aking4125/ca55c1bcba93cfdea3256ba4172f18c1

**Comment by aking4125** [comment]
Nevermind. Sorry. The conflicting mod was [Lavatech.](https://www.curseforge.com/minecraft/mc-mods/lavatech)

**Comment by dysslz** [comment]
![QQ图片20230614195104](https://github.com/someaddons/connectivity/assets/130266380/fa655368-40df-46e1-b10d-1e8bcee0e147)
我是1.19.2可以帮我看看吗mod文件夹需要的找我 GitHUB评论发不出来
谢谢了
