### ISSUE TITLE
[Bug]: Connectivity disables mod commands

### ISSUE THREAD

**Issue by Shikomi36** [someaddons/connectivity#35]
### Describe the bug you're experiencing

in the latest version for 1.18.2, im using connectivity so I don't get kicked for packet sizes (using this to make a datapack faster) and i notice that for one of the mods im using (https://www.curseforge.com/minecraft/mc-mods/kingdom-keys-re-coded/files/3853266) the mod's commands that are loaded in whenever the server finishes loading gets disabled

### Reproducability

install connectivity, install kingdom keys 2, try to use commands

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/Shikomi36/ee813b1e94cf572778eaaee40be39cbe

**Comment by someaddons** [comment]
its because they're not using forge's RegisterCommandsEvent to register their commands properly, not connectivity's fault
