### ISSUE TITLE
[Bug]: Payload may not be larger than 1048576 bytes issue still occurs with mod installed (1.19 Fabric)

### ISSUE THREAD

**Issue by BiggiestBoy** [someaddons/connectivity#36]
### Describe the bug you're experiencing

Im using a very small mod pack but I've been making a huge origins data pack for my Minecraft server so I need a larger packet limit. With this mod installed the issue still shows up.

XLPackest mod fixes this issue, even in single player but that mod isn't the most reliable so I'd prefer not to use it

### Reproducability

Creating a world in single player with this datapack will boot you out of the world with the error Payload may not be larger than 1048576 bytes

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

https://gist.github.com/BiggiestBoy/aed1a368a5f38990457449a6caf464cc

**Comment by someaddons** [comment]
fixed for 1.19 in 3.3
