### ISSUE TITLE
[Bug]: can not login -  String too big

### ISSUE THREAD

**Issue by MSandro** [someaddons/connectivity#37]
### Describe the bug you're experiencing

I can not login to my Modpack server.

### Reproducability

* installing my current Dev-Build Modpack Version. [SF3-0.4.1-dev2.zip](https://github.com/someaddons/connectivity/files/9314199/SF3-0.4.1-dev2.zip)
* create a server by copying the files to a Fabric Server Instance
* remove some client Mods (Sodium, Indium, ...)
* start the server
* join
* fail
![image](https://user-images.githubusercontent.com/10937159/184297661-ee4b0c66-5def-410e-b936-7f310c1db6ba.png)

 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.2

### Modloader version

Fabric

### Logs

https://gist.github.com/MSandro/d82b258379abed78a8bcc0b4fa83aad8

**Comment by someaddons** [comment]
I could circumvent this, but it feels like its more of a techreborn issue
