### ISSUE TITLE
[Bug]: "Payload may not be larger than 1048576 bytes", 1.19 - 3.3

### ISSUE THREAD

**Issue by Uxiut** [someaddons/connectivity#38]
### Describe the bug you're experiencing

Mod is installed alongside 2 origin mods, and the usual fabric stuff on a dedicated server. Just seems to not do its job, here is the server's log:
https://pastebin.com/ikeswKF9

I've got all the same mods, including connectivity on the client too, don't know if that does anything.

### Reproducability

Create a fabric server.
Install the mod, basic fabric requirements
Install apocalypse origins (0.2.27), Origins mod(1.6.2) and origins++ mod(1.7.1)
Start the server
Join with a client with the same mods
Get denied for "invalid player data"

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/Uxiut/156359da285e52a70c59274dd7ea8d44

**Comment by someaddons** [comment]
report to the origins mod, its sending way too much data
