### ISSUE TITLE
[Bug]: Unable to connect to dedicated server.

### ISSUE THREAD

**Issue by DannyDevito747** [someaddons/connectivity#39]
### Describe the bug you're experiencing

Players are booted when attempting to connect, "Payload may not be larger than 1048576 bytes"
All in same chunk.

### Reproducability

Happens to all players attempting to load this chunk.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/DannyDevito747/2e32cf49f203256afd48a516fdcb5ded

**Comment by someaddons** [comment]
Some other mod is causing that chunks data to overflow, should find out which instead
