### ISSUE TITLE
Still Getting Moved Too Quickly Functions on Forge Server

### ISSUE THREAD

**Issue by TJ-Perez** [someaddons/connectivity#4]
Hi, thanks for making this mod! From my understanding, this mod should disable the moved too quickly anti-cheat built into minecraft as a result of limited packet acceptance. This is of course annoying because we would like to be able to fly around without being teleported back. I've been running this on my modded server, and while I feel like we may be getting it less, it still happens with some frequency. I should also note that this is not due to the server running behind, as can be seen in the screenshot below. Thanks for any help!

<img width="928" alt="Screen Shot 2021-06-06 at 10 01 31 AM" src="https://user-images.githubusercontent.com/38085248/120927242-2e665680-c6ae-11eb-86a2-6295c6a65eb7.png">

**Comment by someaddons** [comment]
no the move to quickly doesnt have to do anything with this mod, this mod is about connecting to the server, its not adapting vanilla anticheat stuff
