### ISSUE TITLE
Incompatible with Immersive Portals

### ISSUE THREAD

**Issue by qouteall** [someaddons/connectivity#44]
Log: https://gist.github.com/qouteall/3f9c1043d880e0e11b165009f1a60c59

Reported by DrPineapple
https://discord.com/channels/662271867431682058/671895714527182920/1040104181387776010

**Comment by qouteall** [comment]
Someone reported that it's compatible. Temporary close the issue now.

**Comment by Lolothepro** [comment]
https://github.com/iPortalTeam/ImmersivePortalsModForForge/issues/48
&&
https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1195
