### ISSUE TITLE
[Bug]: Polymer compatiblity patch doesn't work

### ISSUE THREAD

**Issue by Patbox** [someaddons/connectivity#45]
### Describe the bug you're experiencing

After getting https://github.com/Patbox/brewery/issues/4 reported and testing for myself, I found out that Connectivity doesn't apply polymer compatibily patch correctly, breaking it's funtionality.

Seems to be caused by mixin being not registered here https://github.com/someaddons/connectivity/blob/1.19.1fabric/src/main/resources/connectivity.mixins.json

### Reproducability

Install Brewery (https://github.com/Patbox/brewery) and connectivity.
Try creating brewery barrel (singleplayer, but issue could still happen on multi).

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

No direct logs caused by this issue, it fails silently

**Comment by someaddons** [comment]
ye was indeed missing something, fixed in 3.4 should work now

**Comment by Patbox** [comment]
Thanks for fixing and just so you know, with 1.19.4/whatever next release that patch won't be required, asthis bug should be fixed in vanilla. https://bugs.mojang.com/browse/MC-258163

**Comment by Patbox** [comment]
Checked the compat code and it won't work. Since you check with `contains`, it matches any `SMultiBlockChangePacketMixin` in a string, making it also not apply for polymer. You should use endsWith

**Comment by someaddons** [comment]
fixed
