### ISSUE TITLE
[Bug]: Cant connect to Docker Compose Fabric 1.19.2 Modded Server

### ISSUE THREAD

**Issue by xR4YM0ND** [someaddons/connectivity#47]
### Describe the bug you're experiencing

We run a server on docker compose linux Fabric 1.19.2
When Connectivity is installed , the client gets kicked after trying to join. 

- No Crash Report
- [Client latest.log](https://gist.github.com/SpigotDE/7ffedb934af9ad4c9b31e589b52e46a4)
- [Server latest.log](https://gist.github.com/SpigotDE/d347b9bf0846937f39b3cb64b4e8d77d)

![Screenshot 2022-12-28 181354](https://user-images.githubusercontent.com/97298005/209921792-7d453d5c-44e3-474a-bf58-726a4c117f35.png)

### Reproducability

Linux Debian 11
Docker
Docker Compose
Connectivity on Server and Client

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

provided above

**Comment by xR4YM0ND** [comment]
its enough when connectivity is on the client

**Comment by suquiya** [comment]
Same error occured (Just to let mdder know).

**Comment by someaddons** [comment]
how is this related to docker? does it work without?
This is probably just a normal conflict with one of those mods you're running, would need to know which is conflicting to look into

**Comment by someaddons** [comment]
fixed in newest
