### ISSUE TITLE
[Bug]: Origins mod not loading with fabric

### ISSUE THREAD

**Issue by ghost** [someaddons/connectivity#48]
### Describe the bug you're experiencing

Im fairly new to modding a server so forgive me if the reason of my issue is simply stupid, anyways, i have been trying to load a Fabric server with the Origins mod installed, but it refuses to load, I dont know what to do

### Reproducability

I just went to falixnode's website, changed the server to java 17 and fabric 1.19.2, then added origins mod.

btw for the latest.log file, i just copied and pasted what the console said onto a blank sheet, then renamed it

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/Playz07/6db0e6f8ae41468b23b261d354926d22

**Comment by someaddons** [comment]
unrelated to connectivity, you simply installed mods together which use different minecraft versions
