### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kiwicast** [someaddons/connectivity#49]
### Describe the bug you're experiencing

I am using create Flavored Mod Pack, and have been having issues with a warn/error coming up on my console spamming the console for a whole at least 2 minutes at a time and preventing the server from shutting down for minutes.

### Reproducability

It just happens randomly, I am not sure whats triggering it.

When mod is removed the error no longer happens but people have been experiencing connection issues

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/Kiwicast/fa7533875a7b77cef1a1475cd2486c9e#file-gistfile1-txt

**Comment by someaddons** [comment]
connectivity is just displaying the error, some other mods is probably causing it. Next time also post the full log, not just that tiny bit
