### ISSUE TITLE
[Bug]: Huge connection problem, Possible hardware incompatibility

### ISSUE THREAD

**Issue by xArkailzx** [someaddons/connectivity#50]
### Describe the bug you're experiencing

When using connectivity, and ONLY when using connectivity, after a few minutes of gameplay on a dedicated server, connectivity literally makes my Internet adapter CRASH. The adapter is unable to reboot at all and even when rebooting, windows gets stuck on the reboot screen for at least an hour !! I can't play on the server with my friends without connectivity due to a slow connection but I can't play with it as it crashes my internet and glitch out my computer.

Server logs don't contain anything, but client logs seems to have a little info.

### Reproducability

I don't know at all, which is why it's so serious. In worst case, it's an hardware incompatibility and I need to buy an internet adapter.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/xArkailzx/76a6814f83f9b362a90a45ab952cdc2c

**Comment by someaddons** [comment]
minecraft mods don't touch any hardware, they're just doing stuff within minecraft, so your adapter breaking is completly unrelated. You should try completly uninstalling and reinstalling your network adapter driver (download new driver before uninstalling)

**Comment by xArkailzx** [comment]
I already tried to reinstall the driver, with every way possible. However, when I tried to use an external internet adapter, it worked completely fine. So sorry, but useless answer.
