### ISSUE TITLE
[Bug]: With connectivity installed on the server and client, still get disconnected/timed out within 3 minutes (connecting to localhost)

### ISSUE THREAD

**Issue by TheGam1ngWizard** [someaddons/connectivity#51]
### Describe the bug you're experiencing

Setup 1.18 modded server with connectivity on it, joined server, timed out.

### Reproducability

Unknown

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/TheGam1ngWizard/c99daf3bb669500cef0f49041c174af5

**Comment by TheGam1ngWizard** [comment]
Troubleshooting more:

Personal 1.18.2 pack - kicked via timeout
All the mods 7/8 - No issues
All the Mods 7 Skyblock - Game crashes after loading in.

**Comment by someaddons** [comment]
why is this a connectivity issue?
