### ISSUE TITLE
[Bug]: Incompatible with Immersive Portals for Forge

### ISSUE THREAD

**Issue by alexhowell610** [someaddons/connectivity#56]
### Describe the bug you're experiencing

Tried to connect to a server and it never lets me join and spits out an error.

Im on Forge 40.2.1

### Reproducability

1. Install Immersive Portals for Forge and Connectivity
2. Try to connect to a server

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/alexhowell610/a65f72749e0ef1900b43e451462f04fd

**Comment by someaddons** [comment]
I'm no longer updating 1.18, try asking immersive portals
