### ISSUE TITLE
[Bug]: Connectivity "has mods that were not found"

### ISSUE THREAD

**Issue by ElFSonik** [someaddons/connectivity#59]
### Describe the bug you're experiencing

So me and my friend were trying to play with the origins++ mod, we have every depency of origins++ and we have downloaded connectivity because normally the server wouldnt let us in, but everytime we want to launch the game it shows this:
![image](https://user-images.githubusercontent.com/130105434/230497458-4b028276-3bb4-45ca-85b0-78ae2ba584d8.png)

### Reproducability

have this and the connectivity mod 
![image](https://user-images.githubusercontent.com/130105434/230497617-7185809b-e330-4c94-97ae-f2ed46423a5b.png)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/ElFSonik/aa0733d1ff0fa9c1064f8e845affa09c

**Comment by someaddons** [comment]
You're using the fabric version on forge^^
