### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jebjordan** [someaddons/connectivity#6]
Is there any reason for this and performant to not be open source other than just because?

While I'm here:
thanks for making this mod. It works very well. Do wish I could see the source though.

Anyways, have a great day!

**Comment by someaddons** [comment]
I choose my pojects forms according to what I believe suits them the best, aswell as taking time constraints of my freetime into account, so some are closed, some are open, some are visible. Pretty much it depends

**Comment by jebjordan** [comment]
Ah alright thanks for the answer!
Have a great day
