### ISSUE TITLE
[Bug]: Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by wiloxe** [someaddons/connectivity#60]
### Describe the bug you're experiencing

We recently replaced XL Packets with Connectivity and when attempting to place large contraption from create you get kicked with "Payload may not be larger than 32767 bytes"

You also end up in disconnection loop if there are more than 2 people online with the contraption in inventory.

### Reproducability

First construct a drill contraption at size of 10x8 with deployers behind the drills while using barrels as storage. Upon picking up the contraption you will encounter the issue.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/wiloxe/f6fab41905fd8884f50e445ed5733845

**Comment by wiloxe** [comment]
Temporary solution to place the contraption is to feed into a deployer then have it place for you.

**Comment by someaddons** [comment]
ye connectivity does replace a bit less limits on vanillas code, but the actual bug is the mod sending too much data to begin with, it should be fixed on the contraption mod's side. I may add additional limit breaking in the future but won't backport to 1.18
