### ISSUE TITLE
[Bug]: Incompatible with Immersive Portals for Forge 1.19.2

### ISSUE THREAD

**Issue by niraqw** [someaddons/connectivity#61]
### Describe the bug you're experiencing

Trying to join a server with Connnectivity and Immersive Portals for Forge gives the following error: "Internal Exception: java.lang.NullPointerException: Cannot invoke "net.minecraft.network.protocol.Packet.m_5797_(net.minecraft.network.PacketListener)" because "packet" is null"

### Reproducability

1. Install Connectivity and Immersive Portals for Forge on both client and server
2. Try to connect to server

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

Client: https://gist.github.com/niraqw15/59d8dc6509c4deae4d7e04f91cb067c5

Server: https://gist.github.com/niraqw15/acbad491a81fd4e731f3cf2639e3cc75

**Comment by LuizLoyola** [comment]
Confirmed on 1.19.2. Same error.
Mod version: 3.4
Forge version: 43.2.8
Immersive Portals version: 2.3.5

**Comment by someaddons** [comment]
fixed
