### ISSUE TITLE
1.19.2 - Unable to connect to server after updating `` connectivity-1.19.2-3.5.jar`` from ``connectivity-1.19.2-3.4.jar``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [someaddons/connectivity#62]
![TQvRgbc 1](https://user-images.githubusercontent.com/10351221/234688124-1871af1d-a544-4ff9-8100-d1fda3104547.png)

Only changes made
![PrQtTjl 1](https://user-images.githubusercontent.com/10351221/234688497-8d65b54c-3315-4f74-98f9-dd9c6ea69bf2.png)

**Comment by someaddons** [comment]
oh interesting, I had change the limit break to a different place for immersive portals compat, maybe that doesnt work as intended

**Comment by someaddons** [comment]
Do you have the `disableLoginLimits` config option set to true? @P3rf3ctXZer0

**Comment by P3rf3ctXZer0** [comment]
I will check

**Comment by P3rf3ctXZer0** [comment]
> Do you have the `disableLoginLimits` config option set to true? @P3rf3ctXZer0

Yes

https://gist.github.com/P3rf3ctXZer0/5efc98b7f71e2d7d31bb53ce420006d7

**Comment by P3rf3ctXZer0** [comment]
``["Connectivity settings"]
	#Should login packet size limits be disabled? Error:(IOException("Payload may not be larger than 1048576 bytes")) default:true
	disableLoginLimits = true
	#Should play packet size limits be disabled? Error:(Badly compressed packet) default:true
	disablePacketLimits = true
	#If enabled all messages exceeding normal limits will be printed to log. default:false
	debugPrintMessages = false
	#Set the max login timeout in ticks. 20 ticks = 1 sec, default = 120 seconds
	#Range: 600 ~ 20000
	logintimeout = 2400
	#Set the ingame disconnect timeout for disconnecting players. Default = 60sec
	#Range: 15 ~ 400
	disconnectTimeout = 60
	#Set the amount of minutes for which network packet history data is saved. Default = 5 minutes
	#Range: 1 ~ 400
	packetHistoryMinutes = 5
	#Enable to see the full log output for all resource location exceptions. Default = false
	showFullResourceLocationException = false
``

**Comment by ModernGamingWorld** [comment]
I crashed with this mod after updating it in my pack, it crashed with showing alot of mods throwing errors

**Comment by someaddons** [comment]
please refrain from randomly posting comments in a report and instead create a proper new bug report including the logs which would be needed to support you

**Comment by McPersson** [comment]
Same thing. I updated the mod and now when connecting to the server, such an error.

**Comment by P3rf3ctXZer0** [comment]
> please refrain from randomly posting comments in a report and instead create a proper new bug report including the logs which would be needed to support you

Error who is this directed at? Not me I think but I am actually not sure so since I am curious I will just ask. As I am the op of this post XD

**Comment by someaddons** [comment]
> > please refrain from randomly posting comments in a report and instead create a proper new bug report including the logs which would be needed to support you
> 
> Error who is this directed at? Not me I think but I am actually not sure so since I am curious I will just ask. As I am the op of this post XD

someone who apparently now deleted his comment -.-

**Comment by someaddons** [comment]
@P3rf3ctXZer0 could you enable `debugPrintMessages` in your config, reproduce the problem and send me the log? It then should contain the error

**Comment by someaddons** [comment]
try version 3.8

**Comment by P3rf3ctXZer0** [comment]
@someaddons I can definitely do both of these things.

**Comment by P3rf3ctXZer0** [comment]
Not an issue anymore.
