### ISSUE TITLE
[Bug]: Update 3.5 Conflict with XL Packets by tfarecnim due to Mixin redirect 

### ISSUE THREAD

**Issue by Zelioth** [someaddons/connectivity#63]
### Describe the bug you're experiencing

It appears something you changed in the latest update of Connectivity is messing with the mod XL Packets as well. The log states something regarding a mixin redirect. This is a issue only because we use XL Packets in our mod pack due to the amount of mods we currently feature causing packet oversize errors when connecting to servers. 

@ModifyConstant conflict. Skipping connectivity.mixins.json:ClientBoundCustomPayloadPacketLMixin->@ModifyConstant::modifyLimit(I)I with priority 1000, already redirected by xlpackets.mixins.json:SCustomPayloadPacketMixin->@ModifyConstant::xlPackets(I)I with priority 1000

I attempted to reach out to you through the only listed discord on any of your mods. They were not too friendly for me simply just asking if I could draw your attention for a simple conversation. Hope this report helps 

### Reproducability

Install XL Packets version 2.1
Install Connectivity version 3.5 

launch client and will recieve crash 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/Zelioth/63fedfc2efedf770213573c596e0f7a2

**Comment by Zelioth** [comment]
It also seems that the config value of 

	#Should login packet size limits be disabled? Error:(IOException("Payload may not be larger than 1048576 bytes")) default:true
	disableLoginLimits = true
	
	Doesn't work. I have been having to use XL packets since I developed Friends United due to our login authentication process being so large. I've had connectivity added since version 3.3 but doesn't seem to have had any affect on that error

**Comment by Zelioth** [comment]
seems like in 3.5 the disable login packet size feature doesn't function either

**Comment by someaddons** [comment]
Fixed in 3.8, though I'm not sure why you use both to begin with, with connectivity there should be no need for xl packets
