### ISSUE TITLE
Cannot load in my world after update to 4.0

### ISSUE THREAD

**Issue by ghost** [someaddons/connectivity#65]
### Describe the bug you're experiencing

Updated to 4.0, get error every time trying to join my world

### Reproducability

Don't know, Minecraft mods working on magic spells

### Mod up to date

- [x] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/variety754/2139150018fdfeebdb632b9ebacddfc1

**Comment by VeggeieDude** [comment]
I also have this problem. Even in single player, it just tells me "Invalid Player Data"

**Comment by someaddons** [comment]
fixed in 4.1
