### ISSUE TITLE
[Bug]: Crash on start-up [Fabric 1.19.2]

### ISSUE THREAD

**Issue by pokesmells** [someaddons/connectivity#66]
### Describe the bug you're experiencing

When loading into the game, I crash on start-up.

Fabric Version: 0.14.19
MC Version: 1.19.2
Mod Version: connectivity-fabric-1.19.2-4.0
OS Version: Windows 11
Loader Type: Curseforge

### Reproducability

Using the latest version 4.0 causes this.

Crash log: https://mclo.gs/1f3dwEY

Latest log: https://mclo.gs/juEFkrn

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/Poke097/675a8c91265bb8d547bb208d357f2ab9

**Comment by RDP8** [comment]
Same here

**Comment by someaddons** [comment]
fixed in 4.1
