### ISSUE TITLE
[Bug]: `Invalid player data` crash when creating/joining singleplayer world (1.19.4)

### ISSUE THREAD

**Issue by NothingSpecific** [someaddons/connectivity#68]
### Describe the bug you're experiencing

When I try to create or join a singleplayer world I get `Invalid player data` instead of joining the world successfully. This seems to be resolved if I (a) disable Connectivity, or (b) disable every mod except Connectivity, suggesting that it's likely a mod incompatibility.

When trying to debug this error initially I tried disabling all of the obvious mods that might cause the issue (Fast Load, Krypton, REI, Ngrok LAN, Lithium, etc.), so that excludes quite a few of the obvious candidates, but I haven't gone through every mod I had installed to see which one is specifically the issue.

It's also worth noting this only happened when I updated my mods through Prism Launcher. About a week ago everything was compatible, but after the update this error started occurring. So whatever caused this issue was a recent change.

### Reproducability

1. Install the same selection of mods that I have installed
2. Create a singleplayer world OR join an existing singleplayer world
3. That's it! After a few seconds you should see the error

For your convenience I've uploaded a zip of the exact mods I was running when I got this error https://ttm.sh/W7_.4-connec
SHA256: d2edab74c4f1267771eac82a7d7abfcea2c2bbb9354162b53f102cbff1ded9b7

Note: When I disabled Roughly Enough Items I got a slightly different log output. I'm not sure whether this is related or useful, but it might contain additional helpful information. https://mclo.gs/S0D6cHK

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://mclo.gs/5D2tqAz

**Comment by WisperingtoYou** [comment]
It also happens in less recent versions such as 1.19.2 but not in old ones like 1.18.2 and below

**Comment by someaddons** [comment]
fixed in 4.1
