### ISSUE TITLE
[Bug]: Forge 1.19.2 - incompatible with revampedwolf, botania, geckolib, ars nouveau, moonlight, supplementaries and... forge? 

### ISSUE THREAD

**Issue by C0rn3j** [someaddons/connectivity#70]
### Describe the bug you're experiencing

Game just straight out crashes when adding this mod to my existing list

### Reproducability

![image](https://user-images.githubusercontent.com/1641362/235934403-0565a3b6-0ce4-4ce4-97c2-04634f3fda42.png)
[crash-2023-05-03_15.41.34-fml.txt](https://github.com/someaddons/connectivity/files/11383138/crash-2023-05-03_15.41.34-fml.txt)
[latest.log](https://github.com/someaddons/connectivity/files/11383143/latest.log)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

See other fields

**Comment by someaddons** [comment]
it is actually immersive portals causing those issues here when connectivity exists aswell^^

**Comment by someaddons** [comment]
should be fixed in 4.2
