### ISSUE TITLE
[Bug]: connection reset error

### ISSUE THREAD

**Issue by kristinjkristin** [someaddons/connectivity#73]
### Describe the bug you're experiencing

Been playing on server with no issues, player has 'connection reset' error and disconnected from server very frequently.
tried reseting internet and server.

Bisect console looks like attached picture.
![image](https://github.com/someaddons/connectivity/assets/132313585/1b6278cd-5003-4207-8888-d54325e59597)

### Reproducability

Login, play for a few minutes, then gets disconnected.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/kristinjkristin/fce76e361dbec23b592af85a038e0eeb

**Comment by someaddons** [comment]
update to version 4.2
