### ISSUE TITLE
[Bug]: Payload larger than 32767 bytes error still occurs

### ISSUE THREAD

**Issue by StormDragon-64** [someaddons/connectivity#74]
### Describe the bug you're experiencing

In the mod description, it states that the payload too large error has been fixed. However, after installation, I still get kicked from my server due to the same error.

Logs linked are server side, if you need client side too I can supply those.

### Reproducability

I get this error from placing down a minecart contraption from the create mod. There are probably other ways to get this error however.

1. Create a new forge 40.2.0 instance with the Create mod installed (I'm using Create 0.5i which also requires Flywheel) as well as connectivity
2. Create a dedicated server with the same mods and forge version, ect.
3. Join server
4. Create a minecart contraption with a few chests filled with items
5. Pickup minecart contraption
6. Place it back down onto some rails again
❌ Get kicked from server with payload cannot exceed 32767 bytes error

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.2

### Modloader version

Forge

### Logs

https://gist.github.com/StormDragon-64/44b6d809921a31d4d11e15d9250c943d

**Comment by someaddons** [comment]
report it to create, connectivity just alleviates some of the limits but the bug is mods sending too much data to begin with

**Comment by StormDragon-64** [comment]
Create can't fix it because it's an issue with how nbt is stored, but now I'm now using another mod, packet size doubler, that recently updated to fix this issue.

**Comment by Terandox-The-Pineapple** [comment]
I have the same problem, but i don't have create installed.... so its a problem with this mod and not with create.
The fact that this got closed without proper investigation or testing breaks my heart as a programmer and shows me again, that quality died out.
