### ISSUE TITLE
[Bug]: Error spam in log after player diconnects from server.

### ISSUE THREAD

**Issue by KostromDan** [someaddons/connectivity#75]
### Describe the bug you're experiencing

It seems that this error does not affect anything, but spam in the console with an error is not pleasant.

### Reproducability

M-Tech modpack 1.4.1 server. Connect and disconnect.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

[latest.log](https://github.com/someaddons/connectivity/files/11677472/latest.log)

**Comment by someaddons** [comment]
Connectivity does not cause those issues, it simply displays them. Likely on of your other mods causing some problems, might be the pluto mod since it changes networking
