### ISSUE TITLE
[Bug]: Client-side crashes

### ISSUE THREAD

**Issue by DadoIrie** [someaddons/connectivity#76]
### Describe the bug you're experiencing

some really strange error is occuring here
this first crash log happens when executing /locate and upon clicking on the coords client carshes and server states: [Netty Epoll Server IO #0/ERROR] (Minecraft) Exception occurred in netty pipeline
https://mclo.gs/c2G2PKx (crash happening here https://mclo.gs/c2G2PKx#L1134) mouseClicked event handler

then after removing continuity it worked (tried it 3 times and all 3 times same outcome - 4th time without continuity it didn't crashed)

2nd crash - in order to confirm that it is continuity I've enabled continuity again and executed /connectivity packetsClient it didn't showed any packets and 0/kbs
executing same command again it crashed with a keyPressed event handler upon hitting enter to execute command
https://mclo.gs/3EQyeKE (crash happening here https://mclo.gs/3EQyeKE#L1112)

both crashes state that it is ´Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129´

server only logs `[Netty Epoll Server IO #2/ERROR] (Minecraft) Exception occurred in netty pipeline` in both crashes and does not crash

hope this helps finding and fixing the issue

### Reproducability

as explained above

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Fabric

### Logs

https://mclo.gs/3EQyeKE

EDIT: still getting random (and hard to reproduce) `java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129` crashes - therefore most likely connectivity isn't causing it as it was disabled when this occured - feel free to close the issue - any hint though what mod this might be causing would be highly appreciated

**Comment by someaddons** [comment]
from your logs your problems is not network related at all, it is crashing because of a font error, which could be the fault of a client-side mod altering fonts or some custom font resourcepack, not sure. In any case it is unrelated to connectivity, so closing^^
