### ISSUE TITLE
[Bug]: Cannot get kick reason message from velocity server.

### ISSUE THREAD

**Issue by Coder-Iro** [someaddons/connectivity#77]
### Describe the bug you're experiencing

I'm using minecraft account verification system with velocity. When user join verification server (made with velocity), server give 
 authentication code to user using kick reason message. But connectivity installed, It doesn't show kick message, but give `Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 26 out of bounds for length 5` message. In log, It prints `[Netty Client IO #0/WARN] [co.co.Connectivity/]: Packet not registered: ClientboundLoginDisconnectPacket`

### Reproducability

Launch 1.18.2 with forge connectivity, and join `verify.mysticred.space` and compare with vanilla.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.2

### Modloader version

Forge

### Logs

https://mclo.gs/aI69nvZ

**Comment by someaddons** [comment]
not updating 1.18.2 anymore
