### ISSUE TITLE
[Bug]: Hello, I am a staff member at DarkRPG and we are wondering if you have any insights in to this.

### ISSUE THREAD

**Issue by KonekoNyarla** [someaddons/connectivity#78]
### Describe the bug you're experiencing

Not sure if this is even related to you but we are hoping that you may know something about this but we are getting a bug where after a while items that link together for example: chests, fences and walls don't link or the link is broken.

We are unable to replicate this bug as it happens randomly and we were hoping to see if you maybe had someone who has reported the same thing happening or something of this kind.

The most plausible thing is that its related to the server sending invalid/broken block states.

Here is an image of what I am referring to: https://cdn.discordapp.com/attachments/1077294784877695017/1126606768835940403/image.png

### Reproducability

It happens at random and goes away on it's only only affecting the block physics.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

No crashes ever occur and console doesn't report any problems

**Comment by someaddons** [comment]
Does it reset on relog?

**Comment by KonekoNyarla** [comment]
No it doesn't it seems to last for a while and then returns to normal

**Comment by KonekoNyarla** [comment]
We just had it happen a moment ago on our server and it seems to stop all blocks from updating like restone doesn't put out any signal, sand doesn't fall and water doesn't fill after having it removed with a bucket.

**Comment by KonekoNyarla** [comment]
Another update when this bug happens it only affects blocks in the overworld when going in to nether everything works perfectly fine

**Comment by KonekoNyarla** [comment]
I was asked to also include this gif of us placing chests down while this was happening
https://media.discordapp.net/attachments/1077294784877695017/1127767695866200074/javaw_NIMXuX83BV.gif

**Comment by someaddons** [comment]
if a relog did not reset it you're not looking at  a networking issue, but at a mod affecting block placement updates/block states. First station would be trying without performance mods, then any mod which may affect block placement^^
Closing this since not network related

**Comment by KonekoNyarla** [comment]
Restarting the server did fix the issue.
We had a chance to test that today just to confirm that restart does fix the problem.
