### ISSUE TITLE
Issue / Major Inconvenience Regarding Lack Of Server Console Packet Size Feedback.

### ISSUE THREAD

**Issue by Renix4** [someaddons/connectivity#79]
Fabric 1.20.1 Connectivity Version: connectivity-fabric-1.20.1-4.4
 
Huge nuisance impacting Quality Of Life with Mod.

Behavior without mod: When you reach the login packet limit minecrafts server console reports both the packet limit and how large in bytes your login packet is.

Behavior with installed mod: you receive no feedback; server console does not report max packet size, nor reports how large your login packet is.

Description: When you reach the login packet limit by either having way too many recipes, or packet intensive mods like origins and origins++ as well as scripts that load on login (crafttweaker recipes etc) like my modpack "We have TTIGRAAS At Home" recipes no longer load due to your login packet being too large.  This causes JEI, EMI, REI, and the vanilla recipe book to display no recipes at all.    With connectivity installed you receive no feedback on this limit making it hard to troubleshoot what to remove, and how large of an impact what mod you removed made.

Suggestion: Restore server consoles report of this issue with connectivity installed or add functionality to report the login packet impact of every mod the user has installed,  or functionality that splits / separates the login packets the client receives, which would indefinitely extend the amount of mods a user can install.  (My modpack is at the absolute limit and even with ExtraThiccPackets installed, I can no longer add to my modpack)

I'd also like to mention this separate item, the server console reports this message, and I'd like to know what effect this might have:
"[25.07 23:24:15] [Server] [main/WARN]: Mixin 'block.packet.ChunkDeltaUpdateS2CPacketMixin' from 'polymer-core' was disabled by Connectivity Mod (connectivity). Reason: Compat. This might cause issues and isn't generally supported!"

**Comment by someaddons** [comment]
if you want to have debug output enable the debug config
