### ISSUE TITLE
server console warning: login payload registry

### ISSUE THREAD

**Issue by cpm9** [someaddons/connectivity#8]
**Mod file version**
connectivity-2.3-1.16.5.jar

**Describe the bug**
Sorry if this is the wrong place for this. I see this message in my server console near the end of it loading. It says 

[co.co.Connectivity/]: Login payload for Registry minecraft:item is using 37.4838% of max allowed vanilla size

I was just wondering what this warning means and if there is anything I can or should do about it thanks!

**To Reproduce**
1. Start server with connectivity installed

**Expected behavior**
Expected no warning message from connectivity to appear in the server console

**Comment by someaddons** [comment]
You can safely ignore it, its simply for information, because some registries can get too big and cause issues when they go over 100%, esp when the client then doesnt have connectivity

**Comment by cpm9** [comment]
> You can safely ignore it, its simply for information, because some registries can get too big and cause issues when they go over 100%, esp when the client then doesnt have connectivity

Okay thank you. So maybe the label should be Info instead of Warn unless its greater than 100% then it could be Warn?
