### ISSUE TITLE
[Bug]: Fabric/Forge compat problem

### ISSUE THREAD

**Issue by TonimatasDEV** [someaddons/connectivity#81]
### Describe the bug you're experiencing

I have a mod called Packet Fixer that modifies the sizes of all packets, and there is a problem with the NettyCompressiumDecoderMixin. Your mod overwrites the decode method, changing the constant 8388608 to 2097152, this causes some mods like Packet Fixer, that modify the amount of packets to not find the constant and cause minecraft to crash.

### Reproducability

- **1:** Setup a Forge/Fabric server
- **2:** Install Connectivity/Cupboard and Packet Fixer (In this case)
- **3:** Open the client and the server.
- **4:** Try to join the server

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.x, 1.19.x, 1.18.x, 1.16.x

### Modloader version

Forge and Fabric

### Logs

https://gist.github.com/TonimatasDEV/1facedac6b3c66f9f11f21de96781f05

**Comment by someaddons** [comment]
feel free to add compat on your side to it, with connectivity installed I dont really see a reason to add another packet fixing mod. 
If you do not want to crash you should simply mark your mixins as not required so they get skipped instead of crashing

**Comment by TonimatasDEV** [comment]
> feel free to add compat on your side to it, with connectivity installed I dont really see a reason to add another packet fixing mod.
> If you do not want to crash you should simply mark your mixins as not required so they get skipped instead of crashing

I was saying this because there are quite a few people who put different package mods like XLPackets/Packet Fixer together with yours mod, I will do the compatibility, don't worry. Thank you very much for everything.

**Comment by Darkmega18** [comment]
oh good... so... I'm alright or not yet? I kinda need this for a login timeout thing going on... but also for a consistent payload too big thing also happening. 
hoping to see if this helps login time outs. but was actually paranoid about this and packet fixer colliding together and causing issue potentially...

**Comment by TonimatasDEV** [comment]
> oh good... so... I'm alright or not yet? I kinda need this for a login timeout thing going on... but also for a consistent payload too big thing also happening.

Compatibility issues will be resolved in Packet Fixer version 1.1.7. Connectivity is normally used together with Packet Fixer because Connectivity fixes ghost blocks/logging times/network statistics and Packet Fixer fixes all packet sizes and nbt problems.

**Comment by Darkmega18** [comment]
Alright thanks. Will that be released in 1.19.2...? thats the version I need it for. :<

**Comment by TonimatasDEV** [comment]
> Alright thanks. Will that be released in 1.19.2...? thats the version I need it for. :<

For 1.16.5/1.18.2/1.19.2/1.19.4/1.20/1.20.1

**Comment by TonimatasDEV** [comment]
> Alright thanks. Will that be released in 1.19.2...? thats the version I need it for. :<

I have already released 1.1.7 on Modrinth and CurseForge.
