### ISSUE TITLE
[Bug]: Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: 	 - Install cupboard, version 1.19.2-1.5 or later. Unmet dependency listing: 	 - Mod 'Connectivity Mod' (connectivity) 1.19.2-4.5 requires version 1.19.2-1.5 or later of cupboard, which is missing! 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### ISSUE THREAD

**Issue by NessaRinny** [someaddons/connectivity#82]
### Describe the bug you're experiencing

I updated all my mods and now I can't figure out which one is making Minecraft not work but everything is up to date as of 9/18/23

### Reproducability

I updated the mods and that's when I got the crash

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Fabric

### Logs

https://gist.github.com/NessaRinny/34320f5e73e3e990f2a521f63c0017e2

**Comment by someaddons** [comment]
install cupboard mod
