### ISSUE TITLE
[Bug]: Crash game

### ISSUE THREAD

**Issue by M25R4PTOR** [someaddons/connectivity#85]
### Describe the bug you're experiencing

When install mod minecraft don`t run.

I use connectivity-1.20.1-4.6

### Reproducability

Copy the mod to the folder and when you start it crashes.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/M25R4PTOR/bc6e44b5c43ba872de1a0bb9f9d90507

**Comment by someaddons** [comment]
you're missing the cupboard mod dependency
