### ISSUE TITLE
[Bug]: Failed to print data for packet java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by superhealing** [someaddons/connectivity#86]
### Describe the bug you're experiencing

I host ATM9 server, quite few people have issues with connecting the server, people get issue with too big packets, which initially the mod would fix.
Several nodes of packets issue did print, for some reason VM array exceeds, i tried many fixes, nothing solved. If you need more info, i can glandly give more :
ATM9 version : 0.1.12
Forge version : 1.20.1-47.1.3
Connectivity version : `connectivity-1.20.1-4.6.jar`
I enabled debug settings, i give reduced form of debug.log, specifically when player connects, which is posted at logs. I can provide debug.log if is required.

### Reproducability

Sadly, i haven't found a way to reproduce the issue.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

WARNING, IS BIG : https://gist.github.com/superhealing/bcd9aee170e8e24d863faba6b93a5827

**Comment by superhealing** [comment]
I tried to reduce the logs quite large :
https://gist.github.com/superhealing/12d4c4726e2e12e5bb589f920f7f366f

**Comment by someaddons** [comment]
try the newest
