### ISSUE TITLE
Permission for use in Modpack

### ISSUE THREAD

**Issue by t3duk** [someaddons/connectivity#87]
Can I get permission/licensing to use [Connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity) and [Cupboard](https://www.curseforge.com/minecraft/mc-mods/cupboard) in my mudpack if I credit you?

**Comment by someaddons** [comment]
Hi,

Thanks for wanting to include my mods in your modpack. I distribute my mods exclusively on CurseForge, so I only allow them to be included in modpacks hosted on that platform. If your modpack is on CurseForge, feel free to include my mods.

Best regards,

Sam
