### ISSUE TITLE
[Bug]: Error on server startup "Internal Exception: io.netty.handler.codec.EncoderException: Failed to decode: Not a string, Not a list 

### ISSUE THREAD

**Issue by Nariod14** [someaddons/connectivity#88]
### Describe the bug you're experiencing

I haven't played my modpack in a while, and so I got back into it and immediately, and probably unwisely, updated all my mods before starting the game and the server. My modded server used to work perfectly afore this action, but now I'm getting an error when I try connecting to my server, that which you can find in the both the screenshot and the logs that I have attached. While the error seems to be with Origins++ I also noticed the com.connectivity.Connectivity identifiers in the logs, and I through it might be a good idea to post this issue here. Any help would be greatly appreciated!

![image](https://github.com/someaddons/connectivity/assets/21109756/e81fa85e-1949-4cec-8dac-fd457b8589b0)

### Reproducability

This might be modpack specific, but all I did was update my mods and start my exaroton server. The error would pop up on any attempt to join the server.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/Nariod14/41367746843988ef04cdab05184c99ae

**Comment by someaddons** [comment]
ye looks like an origin problem, connectivity just does additional error logging. Since you updated mods make sure you have the same mods and the same config on both server and client

**Comment by Nariod14** [comment]
I've just tested that sadly to no avail. It seems everything is the same and what broke it was updating. Whether it was origins itself that was the issue (i tried downgrading to no avail) or another mod's update that messed it up I'm not sure. I've never seen such an error before and while I do want to I haven't gotten too deeply into the code of modding so I'm not sure where to start. I'd rather not remove the origins mod but if push comes to shove I might have to. Thanks for your prompt reply however!

If you even in passing come up with something I can try please do let me know, and feel free to close this at your discretion as I'm not sure of its relevancy here given the issue is with Origins++

**Comment by someaddons** [comment]
ye I'd just ask the origins author :), anyway unrelated to connectivity
