### ISSUE TITLE
Packet over maximum protocol size

### ISSUE THREAD

**Issue by CloakTheWhat** [someaddons/connectivity#9]
**Mod file version**
1.17.1-2.3

**Describe the bug**
Downloaded this mod to fix the maximum packet protocol size but I still have the problem and I cant get into my server

**To Reproduce**
1. Run Minecraft
2. Join Server
3. See error

**Expected behavior**
For me to join into the server like yesterday

**Screenshots**

![Screenshot (599)](https://user-images.githubusercontent.com/92636191/141254632-86bf6af3-c441-48df-8005-9ac093f3c23a.png)

![Screenshot (600)](https://user-images.githubusercontent.com/92636191/141254578-86c7f7cd-fb5e-46f1-b2a5-79920cf8293c.png)

**Comment by someaddons** [comment]
use the newest 2.4 version, make sure you have it on both sides, server + client and if it still does not work attach the latest.log of both sides to https://gist.github.com/

**Comment by Mysticpasta1** [comment]
Same error but in 1.18.2 forge.
