### ISSUE TITLE
[Bug]: Polymer server error

### ISSUE THREAD

**Issue by DonorKrovi** [someaddons/connectivity#91]
### Describe the bug you're experiencing

https://github.com/Patbox/polymer/issues/91

### Reproducability

https://github.com/Patbox/polymer/issues/91

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://github.com/Patbox/polymer/issues/91

**Comment by Patbox** [comment]
For record, bug that conflicting mixin tries to fix was already fixed in vanilla for few versions

**Comment by DonorKrovi** [comment]
Don't fixed
https://mclo.gs/q9DcYMl
