### ISSUE TITLE
[Bug]: massive lag after joining the server

### ISSUE THREAD

**Issue by Arathorne** [someaddons/connectivity#92]
### Describe the bug you're experiencing

Hello, 
i have a modpack with 312 mods, when i tried adding
![obraz](https://github.com/someaddons/connectivity/assets/60345302/3e326006-1a24-4b6c-8067-6e7f89e14795)
i couldn't log into server beacause of "Paylod may not be larger than 1048576 bytes"
Then i added `connectivity-1.19.2-4.6.jar` to be able to join, however when loaded to world, i started experiencing a massive lag beetwen client and server, in which client was about a minute behind. after the minute it simply disconects the client

### Reproducability

adding 2 mods to 312, after that connectivity, joining server, then you can see the lag between console output and client side

### Mod up to date

- [ ] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2-Forge-43.2.23

### Modloader version

Forge

### Logs

https://gist.github.com/Arathorne/7eed6c9d9442a37e8c83d12fc51694b3

**Comment by someaddons** [comment]
report it to those two mods, connectivity just allows sending larger data, one of those mods is sending massive amounts of data stalling the client
