### ISSUE TITLE
[Bug]: crash with packet fixer

### ISSUE THREAD

**Issue by Thunderrock424242** [someaddons/connectivity#94]
### Describe the bug you're experiencing

i am playing with packet fixer and it crashed 

### Reproducability

play with packet fixer

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/Thunderrock424242/6c7d38f9e8eff2297a92655b742c7cfe

**Comment by someaddons** [comment]
report to packetfixer

**Comment by Thunderrock424242** [comment]
> report to packetfixer

They said they couldn't find an issue with it?
