### ISSUE TITLE
[Bug]: Incompatible with 1.20.4

### ISSUE THREAD

**Issue by PweSol** [someaddons/connectivity#95]
### Describe the bug you're experiencing

Please update your mod to 1.20.4

### Reproducability

 Install latest version with MC 1.20.4

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.4

### Modloader version

Fabric

### Logs

 https://gist.github.com/PweSol/9263f425abfc9916b23743bb5b353f7c

**Comment by someaddons** [comment]
updated to 1.21
