### ISSUE TITLE
[Bug]: Randomly disconnection when joining and playing lan server

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [someaddons/connectivity#96]
### Describe the bug you're experiencing

# IMPORTANT
Playing Modpack: Create Arcane Engineering
# Might be a bug associated with Connectivity
- Randomly disconnecting from other's lan server when playing modpack CAE
- Returning “**illegal packect recieved**”
# Misc
- I saw there reporting "at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23264!/:?]"  so i think might be a bug or sth with network improvement mod( though i didnt see any direct name towards connectivity...)
-  Still happening when disabling connectivity and enable XL PACKET RENEWED(and more error logs, my log went to 500mb+, can u imagine it ??!!!)(this proved connectivity do fix some connection bug)

### Reproducability

# Procedure
1. Start modpack using PCL2
2. Play a while
3. Random disconnection.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.2

### Modloader version

Forge

### Logs

https://mclo.gs/HVkHhDt

**Comment by someaddons** [comment]
in the connectivity config enable `debugPrintMessages` and reproduce the error, then you'll see some causes in the log file

**Comment by someaddons** [comment]
preferably on both client & server, as it may be the server thats kicking you

**Comment by Sorrow-Scarlet** [comment]
thank you, i ll try now

**Comment by Sorrow-Scarlet** [comment]
sry for bothering, but i can't find obvious reason for disconnection, can you give it a try.
# Log
## Client 
https://mclo.gs/E1axfb0
## Host
https://mclo.gs/rvJhb0e

**Comment by someaddons** [comment]
both logs are empty and dont even have a login try in them, are you sure those logs are from during the time you recreated the issue?

**Comment by Sorrow-Scarlet** [comment]
well, i suppose there's some issues with mclo.gs......And this disconnection happened only in CAE modpack....Other modpacks are fine...

**Comment by someaddons** [comment]
ye I guess its a specific mod issue thats sending a bad packet

**Comment by Sorrow-Scarlet** [comment]
> ye I guess its a specific mod issue thats sending a bad packet

got it, maybe i should find CAE's support, i'd just close the issue, thank u
