### ISSUE TITLE
[Bug]: 1.20.1 Crash in Multiplayer Screen

### ISSUE THREAD

**Issue by ToastiMan** [someaddons/connectivity#97]
### Describe the bug you're experiencing

If you go into the Multiplayer Screen, the Servers are stuck on "Pinging" and eventually it will crash after about 2-3 Minutes. If you exit a Server the crash will happen much faster. Removing Connectivity solves the issue. Clean install with just Connectivity and Cupboard will not produce the same problem. Probably Compat Issue.

### Reproducability

As above

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/ToastiMan/c40ac0ccbb131a69878921a375974c81

**Comment by ToastiMan** [comment]
Scratch this, i tested further and it seems to be nochatreports https://github.com/Aizistral-Studios/No-Chat-Reports/issues/460#issue-2078133802

**Comment by someaddons** [comment]
oh interesting, had a similar bug report in another mod where a player was missing the connection, wonder if that is related then too
