### ISSUE TITLE
Consider releasing your mods on Modrinth.

### ISSUE THREAD

**Issue by lunofe** [someaddons/connectivity#98]
As far as I can see this won't be the first time you see someone opening an issue about your mod(s) not being available on Modrinth.

However you've never specified a reason as to why this is the case.

I'd like you to (re?)consider releasing your mods on Modrinth as it's an open-source alternative to CurseForge that has attracted many users lately due to the release of their own launcher.

During this year, downloads of my modpack have shifted from 90% CurseForge, 5% Technic & **5%** Modrinth to 60% CurseForge, 3% Technic & **37%** Modrinth.

It's very irritating for modpack creators to deal with inconsistencies between major platforms and I assume I'm not the only one that **would like** to make use of your mod, **but can't**.

If you, for some reason, plan to never release on Modrinth, please allow modpack creators to redistribute your mod(s) on Modrinth.

**Comment by lunofe** [comment]
Well, thanks for your answer @someaddons.

**Comment by xllifi** [comment]
It's honestly just confusing at this point. Only feature modrinth lacks over CurseForge is comments. A few years ago it was monetization, which is a great reason, but now modrinth has implemented it.

**Comment by Viper4K** [comment]
> It's honestly just confusing at this point. Only feature modrinth lacks over CurseForge is comments. A few years ago it was monetization, which is a great reason, but now modrinth has implemented it.

and they have better security, because unlike curseforge they actually do check what gets uploaded, avoiding "so we found out there is another virus on our site, don't download mods for some time" bs
