### ISSUE TITLE
[Clarification] Server VS Client configs.

### ISSUE THREAD

**Issue by Waterspark63** [someaddons/connectivity#99]
Quick question, do the client and server side configs need to be the same on both sides, or is it fine if they differ? Wanted to make sure as I'm trying to troubleshoot some networking issues I'm having. Also, the logintimeout config option is meant to increase the timeout before being kicked for taking too long to log in correct? It doesn't seem to have any effect on my server (1.20.1-5.6). Players still get kicked after the default timeout period.

**Comment by someaddons** [comment]
its fine if they differ. Hm it should work and increase the timeout migh be some other error during login. Btw for login issues I also recommend using my "Chunk Sending" mod which lightens the load during login(not so many chunks sent at once)
